version: "{branch}-{build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  # spotlessJavaCheck fails on AppVeyor, so just run tests (see #15)
  - gradlew.bat test --info --no-daemon

environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  fast_finish: true

cache:
  - '%USERPROFILE%\.gradle\wrapper -> gradle\wrapper\gradle-wrapper.properties'
