name: "Validate Gradle Wrapper"
  push:
    branches: 'master'
    tags-ignore:
      - 'v**'
      - 'releaseTrigger'
  pull_request:
    branches: '*'

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
