name: Release build

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: on ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Wait on builds
        uses: lewagon/wait-on-check-action@v0.1-beta.2
        with:
          ref: ${{ github.sha }}
          check-name: buildOk
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 300
      - name: Set up java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Perform release
        uses: eskatos/gradle-command-action@v1
        env:
          # used by `io.github.gradle-nexus.publish-plugin` to sign artifacts
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.JUNIT_PIONEER_PGP_SECRET_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.JUNIT_PIONEER_PGP_PASSWORD }}
          # used by `io.github.gradle-nexus.publish-plugin` to publish to Maven Central
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.NEXUS_TOKEN_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.NEXUS_TOKEN_PASSWORD }}
        with:
          arguments: publishToSonatype closeAndReleaseSonatypeStagingRepository githubRelease
      - name: Trigger website build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_WRITE_TOKEN }}
          repository: junit-pioneer/junit-pioneer.github.io
          event-type: triggerSiteBuild
